### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Cazzi**

### CODE REVIEW

**Comment by Cazzi** [comment]
Fixes + EditDishActivity

**Comment by Cazzi** [comment]
Drawerlayout added, main activity still has big useless buttons and needs polishing

**Comment by Cazzi** [comment]
Back button in all activities

**Comment by Cazzi** [comment]
Header still is in need for a background

**Comment by Cazzi** [comment]
Almost done with the graphical stuff

**Comment by giovannic96** [comment]
Please next time create your own branch according to the changes and then make pull request with that branch (then yo can merge into master in your pc) for better clarity. Thank you

**Comment by giovannic96** [comment]
Application crashes in daily offer activity. Probably problems with URI image. Please fix it before making pull request.

**Comment by giovannic96** [comment]
Application crashes also when quantity is null (numbers cancelled by user) while pressing plus or minus button

**Pull request merged**
